language: cpp
sudo: true
compiler:
- gcc
os:
- linux
before_install:
- unset CXX
- unset CC
script:
  - travis_retry ./build.sh
env:
  global:
    - USE_PICKLE=1
    - USE_JOBS_OVERRIDE=-j4
    - secure: "M29jAyyAO/RCCvsSN+5hVn2Y9/um2qb2h7hZNZB0nFYvfZrkO/SKWCOrNNU/GALy8Bcbe42VjoJ8t9cS6nKXM+ClhqOwUSnHQwi2keAQhxjEdC9WlJXb2XnYIEias2X3g5epYiNJrNkIi+P+lSpKUzib0taYbCfEKqiGQf3Q8bP/DSFX7VQgH3V6Ce07dxroBU9a3RbJXsXPiHHWB8FbgzQW/ZzFUXDnf+uLDfildV1ag2pn0lA1DzEXQ5HZZwO/rnFNsiwJYhq5OrpvbsTtRMaS3ylsichD4bdpdwQGqQo+wX01okFCl11rosXVbCbQUWvvmhZC+gNlkhLi+BmvorSdJNtI3U9MIPDY+ZRyunvaw+DKEIOSLtE1xJ4k7L6tTlDyyIyzj+cgC77d5Uzypqz5aoBb8l3P4pGd8GUXSm6nR0+4LD4Y7VGKc3hU71Ny7ydKcJskICu1zn2t2cXuDZ2yvwpfd5ODPWhezsjAmA6hgcsUoOkZoaImu13UzBdFgSfPCE3akJmZyPnrnJZ7BODrcWadsCf6kVipBL6LbB3s9SVm++MxiTdOEN6i4+dvZgp8Al3UpH08UdB0bkx7mKzP9CtlaNCCyyAMZDkt+dW1i5r7qhjzjjoON5Esj+vnK2Zp4DnieNudg4I9MUCLnr42WhqUEMQzsSSx0aL3tBk="
  matrix:
    - PLATFORM=linux64
    - PLATFORM=android
after_success:
  - .travis/github-mirror.sh 'vsimon/webrtcbuilds' `cat out/revision_number` out/src
  - .travis/github-release.sh 'vsimon/webrtcbuilds' `cat out/revision_number` out/*.zip
